const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  user: process.env.DB_USER,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port: process.env.DB_PORT,
});

// Handle successful connection
pool.on('connect', () => {
  console.log('Successfully connected to the database');
  createTableIfNotExists();
});

// Handle errors
pool.on('error', (err) => {
  console.error('Database pool error:', err.stack);
});

// Function to create messages table if it doesn't exist
async function createTableIfNotExists() {
  try {
    const createTableQuery = `
      CREATE TABLE IF NOT EXISTS messages (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        sid VARCHAR(34) NOT NULL,
        to_number VARCHAR(15) NOT NULL,
        from_number VARCHAR(15) NOT NULL,
        body TEXT NOT NULL,
        status VARCHAR(20) NOT NULL,
        direction VARCHAR(10) NOT NULL,
        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
      )
    `;

    await pool.query(createTableQuery);
    console.log('Table "messages" checked/created successfully');
  } catch (err) {
    console.error('Error creating table:', err.stack);
  }
}

module.exports = pool;