const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  user: process.env.DB_USER,
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port: process.env.DB_PORT,
});

pool.on('connect', () => {
  console.log('Successfully connected to the database');
  createTableIfNotExists();
});

pool.on('error', (err) => {
  console.error('Database pool error:', err.stack);
});

async function createTableIfNotExists() {
  try {
    const checkTablesExistQuery = `
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_name IN ('messages', 'shortened_urls');
    `;

    const result = await pool.query(checkTablesExistQuery);
    const existingTables = result.rows.map(row => row.table_name);

    if (!existingTables.includes('messages')) {
      const createMessagesTableQuery = `
        CREATE TABLE messages (
          id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
          sid VARCHAR(50) NOT NULL,
          to_number VARCHAR(15) NOT NULL,
          from_number VARCHAR(15) NOT NULL,
          body TEXT NOT NULL,
          status VARCHAR(20) NOT NULL,
          direction VARCHAR(10) NOT NULL,
          message_id VARCHAR(50) NULL,
          created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
        )
      `;
      await pool.query(createMessagesTableQuery);
      console.log('Table "messages" created successfully');
    } else {
      console.log('Table "messages" already exists');
    }

    if (!existingTables.includes('shortened_urls')) {
      const createShortenedUrlsTableQuery = `
        CREATE TABLE shortened_urls (
          id SERIAL PRIMARY KEY,
          short_id VARCHAR(8) NOT NULL UNIQUE,
          original_url TEXT NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `;
      await pool.query(createShortenedUrlsTableQuery);
      console.log('Table "shortened_urls" created successfully');
    } else {
      console.log('Table "shortened_urls" already exists');
    }
  } catch (err) {
    console.error('Error creating tables:', err.stack);
  }
}

module.exports = pool;